### ISSUE TITLE
第十题的价格没有处理

### ISSUE THREAD

**Issue by jiechen257** [gaoxiaoxin/LanQiaoBei-Web#1]
第十题 *carlist数据* 中的 `price` 字段要进行额外处理，如 `6800 处理成 68.00`

**Comment by gaoxiaoxin** [comment]
哈哈，真的很细心，你不说我都没看见，但是我感觉这个不应该由我们个人去判断价格，因为它数据中和题目中并没有给出明确的要求去让我们用那种格式划分价格，这个应该是题目给定的数据的问题

**Comment by gaoxiaoxin** [comment]
https://gaoxiaoxin.github.io/2022/04/09/%E6%9D%82%E9%A1%B9/%E8%93%9D%E6%A1%A5%E6%9D%AF%E9%A2%98%E8%A7%A3/                      我写了题解，来看看吧

**Comment by jiechen257** [comment]
你这让我苦笑不得（2333   我就是为了处理价格的转换多花费了半小时还没有实现好，要是不用处理我真的会谢（23333

**Comment by jiechen257** [comment]
还有一点不知道你留意没，数据中 `"name": "经典项目：前后端分离网盘系统实战",` 这一条数据中没有 `price`字段 ，在题目给的gif示例里是显示的 `NaN` ，但是我们应该怎么去显示它
![image](https://user-images.githubusercontent.com/73946940/162610209-39755d34-acb2-4b10-8268-44cbbea68838.png)

**Comment by jiechen257** [comment]
另外，作者麻烦看下第九题的答案，这个判断类型的处理逻辑 **必需** 吗，我在跟赛友讨论这点，如果不加的话，有没有可能它`测试用例` 没有极端情况，没有测试出来,然后答案算作正确的
![image](https://user-images.githubusercontent.com/73946940/162610485-a7994bbd-295e-4c18-a44a-837205a2a1f9.png)

**Comment by gaoxiaoxin** [comment]
![image](https://user-images.githubusercontent.com/79193821/162610611-1508b5cd-dc08-4cfc-a80b-31ca492cf2c2.png)
如果想实现小数点的话，其实可以这样。 可以发现它是保留了小数点后2位

**Comment by gaoxiaoxin** [comment]
> 还有一点不知道你留意没，数据中 `"name": "经典项目：前后端分离网盘系统实战",` 这一条数据中没有 `price`字段 ，在题目给的gif示例里是显示的 `NaN` ，但是我们应该怎么去显示它 ![image](https://user-images.githubusercontent.com/73946940/162610209-39755d34-acb2-4b10-8268-44cbbea68838.png)

这个我没发现哈哈，因为只考虑了整体的技术实现，没有发现少一个数据，这个我感觉也是官方要背锅

**Comment by gaoxiaoxin** [comment]
> 另外，作者麻烦看下第九题的答案，这个判断类型的处理逻辑 **必需** 吗，我在跟赛友讨论这点，如果不加的话，有没有可能它`测试用例` 没有极端情况，没有测试出来,然后答案算作正确的 ![image](https://user-images.githubusercontent.com/73946940/162610485-a7994bbd-295e-4c18-a44a-837205a2a1f9.png)

这个的话，我更想把这个称为一个开发习惯，错误优先原则，先在开头排除错误的情况，防止错误的情况进入我们的逻辑代码

**Comment by jiechen257** [comment]
> > 另外，作者麻烦看下第九题的答案，这个判断类型的处理逻辑 **必需** 吗，我在跟赛友讨论这点，如果不加的话，有没有可能它`测试用例` 没有极端情况，没有测试出来,然后答案算作正确的 ![image](https://user-images.githubusercontent.com/73946940/162610485-a7994bbd-295e-4c18-a44a-837205a2a1f9.png)
> 
> 这个的话，我更想把这个称为一个开发习惯，错误优先原则，先在开头排除错误的情况，防止错误的情况进入我们的逻辑代码

这么说的话，如果不加这个判断，且它测试用例的 cb 参数存在不是 function 类型，然后也跳进函数里面报错，这算是答题失败了吗

**Comment by gaoxiaoxin** [comment]
这次第一届蓝桥杯，官方多多少少有带着试水的目的，Web开发的比赛人数偏少，一些官方的bug发现并不及时， 起码在比赛中并没有发现官方有公告Web的漏洞。

**Comment by gaoxiaoxin** [comment]
> > > 另外，作者麻烦看下第九题的答案，这个判断类型的处理逻辑 **必需** 吗，我在跟赛友讨论这点，如果不加的话，有没有可能它`测试用例` 没有极端情况，没有测试出来,然后答案算作正确的 ![image](https://user-images.githubusercontent.com/73946940/162610485-a7994bbd-295e-4c18-a44a-837205a2a1f9.png)
> > 
> > 
> > 这个的话，我更想把这个称为一个开发习惯，错误优先原则，先在开头排除错误的情况，防止错误的情况进入我们的逻辑代码
> 
> 这么说的话，如果不加这个判断，且它测试用例的 cb 参数不存在是 function 类型，然后也跳进函数里面报错，这算是答题失败了吗

这个的话，其实官方的目的是想让我们手写 filter 方法的实现，而 原生的 filter 方法的调用就是传入 回调函数 , 所以加这个判断是有必要的, 如果没加的话报错，这个我们其实也可以理解成调用方法的方式不对而报的错，对方法的使用者的一个提醒。

**Comment by jiechen257** [comment]
> > > > 另外，作者麻烦看下第九题的答案，这个判断类型的处理逻辑 **必需** 吗，我在跟赛友讨论这点，如果不加的话，有没有可能它`测试用例` 没有极端情况，没有测试出来,然后答案算作正确的 ![image](https://user-images.githubusercontent.com/73946940/162610485-a7994bbd-295e-4c18-a44a-837205a2a1f9.png)
> > > 
> > > 
> > > 这个的话，我更想把这个称为一个开发习惯，错误优先原则，先在开头排除错误的情况，防止错误的情况进入我们的逻辑代码
> > 
> > 
> > 这么说的话，如果不加这个判断，且它测试用例的 cb 参数不存在是 function 类型，然后也跳进函数里面报错，这算是答题失败了吗
> 
> 这个的话，其实官方的目的是想让我们手写 filter 方法的实现，而 原生的 filter 方法的调用就是传入 回调函数 , 所以加这个判断是有必要的, 如果没加的话报错，这个我们其实也可以理解成调用方法的方式不对而报的错，对方法的使用者的一个提醒。

好的，谢谢你的答疑（rose rose rose
